spring:
   application:
       name: mad-machine-assessment
   datasource:
     url: jdbc:h2:file:~/testdb
     driver-class-name: org.h2.Driver
     username: sa
     password: password
     schema: classpath:schema.sql
   jpa:
     hibernate:
       ddl-auto: update   # This prevents JPA from modifying the schema, so it won't try to recreate the table
       show-sql: true
     database-platform: org.hibernate.dialect.H2Dialect
     defer-datasource-initialization: true
   h2:
    console.enabled: true

server:
  port: 8090